version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ratemysoft-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ratemysoft
      POSTGRES_USER: ratemysoft_user
      POSTGRES_PASSWORD: ratemysoft_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ratemysoft_user -d ratemysoft"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
