// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Website   *string            `json:"website"`
	Slug      string             `json:"slug"`
	LogoUrl   *string            `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Credential struct {
	UserID     uuid.UUID          `json:"user_id"`
	Provider   string             `json:"provider"`
	Identifier string             `json:"identifier"`
	SecretHash *string            `json:"secret_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Category     string             `json:"category"`
	ShortTagline *string            `json:"short_tagline"`
	Description  *string            `json:"description"`
	HomepageUrl  *string            `json:"homepage_url"`
	DocsUrl      *string            `json:"docs_url"`
	AvgRating    *float64           `json:"avg_rating"`
	TotalReviews int32              `json:"total_reviews"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Review struct {
	ID            uuid.UUID          `json:"id"`
	ProductID     uuid.UUID          `json:"product_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Title         *string            `json:"title"`
	Body          string             `json:"body"`
	Rating        int32              `json:"rating"`
	Status        string             `json:"status"`
	UpvoteCount   int32              `json:"upvote_count"`
	DownvoteCount int32              `json:"downvote_count"`
	FlagCount     int32              `json:"flag_count"`
	Edited        bool               `json:"edited"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Handle    string             `json:"handle"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
